name: Deploy to Docker

on:
  - push
  - workflow_dispatch

jobs:
  build:
    # ubuntu latest is not contains Python 3.6
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install coveralls
      - name: Test
        run: python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests
      - name: Push test coverage to Coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: clooooode/pyfun-backend:latest
