name: Validation of new Stage or Lesson

on: [ pull_request ]

jobs:
  build:
    # ubuntu latest is not contains Python 3.6
    runs-on: ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install coveralls
      - name: Test
        run: python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests
      - name: Push test coverage to Coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls
